name: Core
version: '${version}'
main: dev.aledlb.Core
api-version: '1.13'
authors: [aledlb]

load: POSTWORLD

depend:
  - Vault
softdepend:
  - PlaceholderAPI

commands:
  core:
    description: Core plugin command
    usage: /core
    aliases: [c]
  permission:
    description: Manage permissions
    aliases: [perm]
    permission: core.permission
    default: op
  freeze:
    description: Freeze a player
    usage: /freeze <player>
    permission: core.freeze
    default: op
  mute:
    description: Mute a player
    usage: /mute <player> [reason]
    permission: core.mute
    default: op
  unmute:
    description: Unmute a player
    usage: /unmute <player>
    permission: core.mute
    default: op
  gmc:
    description: Change gamemode to creative
    usage: /gmc
    aliases: [creative]
    permission: core.gamemode
    default: op
  gms:
    description: Change gamemode to survival
    usage: /gms
    aliases: [survival]
    permission: core.gamemode
    default: op
  gma:
    description: Change gamemode to adventure
    usage: /gma
    aliases: [adventure]
    permission: core.gamemode
    default: op
  gmsp:
    description: Change gamemode to spectator
    usage: /gmsp
    aliases: [spectator]
    permission: core.gamemode
    default: op
  fly:
    description: Enable or disable fly mode
    usage: /fly
    permission: core.fly
    default: op
  vanish:
    description: Enable or disable vanish mode
    usage: /vanish
    aliases: [v]
    permission: core.vanish
    default: op
  enchantgui:
    description: Open the enchantment GUI.
    usage: /enchantgui
    aliases: [egui]
    permission: core.enchantgui
    default: op
  kit:
    description: Manage kits.
    usage: /kit [save] <kitName>
    permissions: core.kit.save
  broadcast:
    description: Broadcast a message to the entire server.
    usage: /broadcast <message>
    permission: core.broadcast
  feed:
    description: No more hungry boy.
    usage: /feed
    permission: core.feed
  heal:
    description: Save that ass.
    usage: /heal
    permission: core.heal
  more:
    description: Get more of the item you're holding.
    usage: /more
    permission: core.more
  rename:
    description: Rename an item you're holding.
    usage: /rename <displayName>
    permission: core.rename
  addlore:
    description: Adds a lore to the item you're holding.
    usage: /addlore <lore>
    permission: core.addlore
  removelore:
    description: Removes a lore from the item you're holding.
    usage: /removelore <number>
    permission: core.removelore
  keepinventory:
    description: Enables user to keep the inventory after death.
    usage: /keepinventory
    permission: core.keepinventory
  chathistory:
    description: View or clear a player's chat history
    usage: /chathistory <player> [list|clear]
    permission: core.chathistory
    default: op
  inventorybackup:
    description: Manage player inventory backups
    usage: /inventorybackup <player> [save|load|list|delete]
    permission: core.inventorybackup
    default: op
  location:
    description: Manage player locations
    usage: /location <player> [save|load|list|delete]
    permission: core.location
    default: op
  playerstats:
    description: View player statistics
    usage: /playerstats <player>
    permission: core.playerstats
    default: op
  tempban:
    description: Temporarily ban a player
    usage: /tempban <player> <duration> <reason>
    permission: core.tempban
    default: op
  unban:
    description: Unban a player
    usage: /unban <player>
    permission: core.unban
    default: op
  warn:
    description: Warn a player
    usage: /warn <player> <reason>
    permission: core.warn
    default: op
  unwarn:
    description: Remove a warning from a player
    usage: /unwarn <player>
    permission: core.unwarn
    default: op
  chatfilter:
    description: Manage chat filter rules
    usage: /chatfilter <add|remove|list|reload> [name] [pattern] [action] [message]
    permission: core.chatfilter
    default: op

permissions:
  core.permission:
    description: Allows managing permissions
    default: op
  core.keepinventory:
    description: Allows using command
    default: op
  core.freeze:
    description: Allows freezing players
    default: op
  core.freeze.bypass:
    description: Allows bypassing the freeze
    default: op
  core.mute:
    description: Allows muting players
    default: op
  core.gamemode:
    description: Allows changing gamemode
    default: op
  core.fly:
    description: Allows enabling or disabling fly mode
    default: op
  core.vanish:
    description: Allows enabling or disabling vanish mode
    default: op
  core.vanish.see:
    description: Allows seeing vanished players
    default: op
  core.kit.*:
    description: Access to all kit
    default: op
  core.kit.save:
    description: Allows saving kits
    default: op
  core.kit.load:
    description: Allows loading kits
    default: op
  core.kit.delete:
    description: Allows deleting kits
    default: op
  core.kit.list:
    description: Allows listing kits
    default: op
  core.enchantgui:
    description: Allows opening the enchantment GUI
    default: op
  core.chathistory:
    description: Allows viewing and clearing chat history
    default: op
  core.inventorybackup:
    description: Allows managing inventory backups
    default: op
  core.location:
    description: Allows managing player locations
    default: op
  core.playerstats:
    description: Allows viewing player statistics
    default: op
  core.tempban:
    description: Allows temporarily banning players
    default: op
  core.unban:
    description: Allows unbanned players
    default: op
  core.warn:
    description: Allows warning players
    default: op
  core.unwarn:
    description: Allows removing warnings from players
    default: op
  core.chatfilter:
    description: Allows managing chat filter rules
    default: op
  core.chatfilter.bypass:
    description: Allows bypassing chat filter rules
    default: op
  core.broadcast:
    description: Allows broadcasting messages
    default: op
  core.feed:
    description: Allows feeding players
    default: op
  core.heal:
    description: Allows healing players
    default: op
  core.more:
    description: Allows getting more items
    default: op
  core.rename:
    description: Allows renaming items
    default: op
  core.addlore:
    description: Allows adding lore to items
    default: op
  core.removelore:
    description: Allows removing lore from items
    default: op